type MyOrchardDU = | NumAppleTrees of int |  NumPearTrees of int 
// can have any number of apple or pear trees but not both

type A = ...
type B = ...
type C = ...
type MyDU = | Thing of A | Person of B * C | Weird
